### ISSUE TITLE
SBDynamicWaterNode not working properly for iOS 8.1.2

### ISSUE THREAD

**Issue by smindia1988** [SteveBarnegren/DynamicWaterNode#1]
I have used SBDynamicWaterNode and tested it. Its working fine with iOS 9.0 but having issue in iOS 8.1.2
Please correct and update it.

**Comment by SteveBarnegren** [comment]
I'll take a look when I have time, although I can't promise at what point that will be at the moment.

If you can provide me with some more information about the unexpected behaviour that you're seeing that would be great. If is crashing for you, what line on? Is there any console output that may give some indication about what the error might be?

Also, is this in the simulator, or on device? And if so, what device?

**Comment by smindia1988** [comment]
I have tested on device with iOS 8.1.2. When drop effect produce, water node will behave weird. It will resize to slide small, position get changed and effect looks weird.

 You can reproduce this scenario by just directly launching app in iOS 8.1.2 and put the stone to make drop effect (by clicking).

It will not crash anymore. I tried to understand this weird issue but didn't identify. Working fine for other iOS. This might be ios version specific issue.

**Comment by SteveBarnegren** [comment]
Closing this now. Unfortunately I didn't have time to look in to it at the time, and now that we're on iOS 11, it's probably not worth fixing.
